version: "3.9"
services:
  postgres:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql

  processing:
    build:
      context: ./job
    container_name: processing_job_app
    environment:
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - postgres

  webapp:
    build:
      context: ./app
    container_name: web_app
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    depends_on:
      - postgres
      - processing
    ports:
      - "5000:5000"
